### ISSUE TITLE
No module named 'mistune'

### ISSUE THREAD

**Issue by oskarko** [lepture/mistune#119] opened 2016-09-28 13:53 UTC
I'm traying to use it in my project. I use mac osx and anaconda. I download it with "pip install mistune". It says v0.7.3 is downloaded and installed but when I run the server and try it... it crash! and that the message I get it: No module named 'mistune'.

any good solution?

**Comment by lepture** [comment] 2016-09-29 02:10
Not a bug in mistune. Close it now.

You can `pip install mistune` and try `import mistune` in your python repl.

**Closed by lepture** 2016-09-29 02:10 UTC
