### ISSUE TITLE
MathJax "blocks" not like expected.

### ISSUE THREAD

**Issue by bollwyvl** [lepture/mistune#45] opened 2015-03-20 15:52 UTC
Over on IPython, we've run into a regression from our previous markdown toolchain.

Previously, something like this:

``` markdown
$math$
$$
big math
$$
$other math
```

Would render up an inline, a block and an inline. At present, the recipe in contrib and in the tests here, as implemented in IPython, creates _interesting_ problems, as something happens to this pattern, and it doesn't render properly:
https://github.com/jupyter/nbviewer/issues/420
https://github.com/jupyter/nbviewer/issues/422

We "fixed" it by making inline ALSO match block math:
https://github.com/ipython/ipython/pull/8066/files

If you have any insight into how we might fix this more elegantly, that would be greatly appreciated!

**Comment by lepture** [comment] 2015-05-28 11:55
@bollwyvl Is there a test case for this issue? What should I expect when I put something in the parser?

**Comment by bollwyvl** [comment] 2015-05-28 13:03
Thanks for the response!

Here's what made it into IPython:
https://github.com/ipython/ipython/pull/8066/files

Test cases are at the bottom... they are taken from real notebooks that people reported were acting strangely.

**Comment by f-koehler** [comment] 2015-09-16 21:19
I am currently trying to hack mistune as well. I implemented math in a similiar way to IPython and mistune-contrib. I have a problem with inline math. I wrote a minimal example that reproduces the issue:
```python
import mistune
import re

class InlineGrammar(mistune.InlineGrammar):
    math = re.compile("^\$\$(.+?)\$\$", re.DOTALL)

class InlineLexer(mistune.InlineLexer):
    default_rules = ["math"] + mistune.InlineLexer.default_rules

    def __init__(self, renderer, **kwargs):
        rules = InlineGrammar()
        super(InlineLexer, self).__init__(renderer, rules, **kwargs)
    
    def output_math(self, m):
       return self.renderer.inline_math(m.group(1))

class Renderer(mistune.Renderer):
    def inline_math(self, text):
        return "@@%s@@" % text

md = mistune.Markdown(Renderer(), inline=InlineLexer(Renderer()))
print(md.render(r"$$\begin{pmatrix}a \\ b\end{pmatrix}$$"))
print(md.render(r"Just some text $$\begin{pmatrix}a \\ b\end{pmatrix}$$ around my math"))
```

This code should yield the output
```html
<p>@@\begin{pmatrix}a \\ b\end{pmatrix}@@</p>

<p>Just some text @@\begin{pmatrix}a \\ b\end{pmatrix}@@ around my math</p>

```
but results in
```html
<p>@@\begin{pmatrix}a \\ b\end{pmatrix}@@</p>

<p>Just some text $$\begin{pmatrix}a \ b\end{pmatrix}$$ around my math</p>

```
The problem is that in the second case the regex for inline_math does not match. But I do not know why.

Any ideas?

**Comment by lepture** [comment] 2019-12-07 12:49
closing it since it is not mistune itself.

**Comment by lepture** [comment] 2019-12-07 12:50
v2.0.0a1 has new plugin system.

**Closed by lepture** 2019-12-07 12:49 UTC
Labels: contrib, question
